#!/usr/bin/env python3
"""
encrypt.py — encrypt a .jkb file into a C header for embedding in jockstrap.

Usage:
    python encrypt.py test.jkb jockey_runner_encrypted.h

The generated header defines:
    extern const uint8_t  encrypted_bytecode[];
    extern const uint32_t encrypted_bytecode_len;
    extern const char     bytecode_filename[];
"""

import sys
import os

RC4_KEY = b"jky-runner-2026"
XOR_KEY = 0x5a


def rc4_encrypt(data: bytes, key: bytes) -> bytes:
    S = list(range(256))
    j = 0
    for i in range(256):
        j = (j + S[i] + key[i % len(key)]) & 0xff
        S[i], S[j] = S[j], S[i]
    out = bytearray(len(data))
    a = b = 0
    for k in range(len(data)):
        a = (a + 1) & 0xff
        b = (b + S[a]) & 0xff
        S[a], S[b] = S[b], S[a]
        out[k] = data[k] ^ S[(S[a] + S[b]) & 0xff]
    return bytes(out)


def encrypt(data: bytes) -> bytes:
    """XOR single-byte pass, then RC4 stream cipher."""
    xored = bytearray(b ^ XOR_KEY for b in data)
    return rc4_encrypt(bytes(xored), RC4_KEY)


def c_escape(data: bytes) -> str:
    """Format bytes as a C initializer list, 12 per line."""
    chunks = []
    for i in range(0, len(data), 12):
        line = ", ".join(f"0x{b:02x}" for b in data[i:i+12])
        chunks.append("    " + line)
    return ",\n".join(chunks)


def main():
    if len(sys.argv) < 3:
        print("usage: encrypt.py <input.jkb> <output.h>")
        sys.exit(1)

    src = sys.argv[1]
    dst = sys.argv[2]
    fname = os.path.basename(src).encode("utf-8")

    with open(src, "rb") as f:
        plain = f.read()

    encrypted = encrypt(plain)
    print(f"input:  {len(plain)} bytes")
    print(f"output: {len(encrypted)} bytes")

    guard = dst.replace(".", "_").upper() + "_"

    header = f"""\
#ifndef {guard}
#define {guard}

#include <stdint.h>
#include <stddef.h>

/*
 * Encrypted Jockey bytecode blob.
 * Generated by encrypt.py — do not edit.
 * Original file: {fname.decode()}
 */
static const uint8_t  encrypted_bytecode[] = {{
{c_escape(encrypted)}
}};
static const uint32_t encrypted_bytecode_len = {len(encrypted)};
static const char     bytecode_filename[] = "{fname.decode()}";

#endif /* {guard} */
"""

    with open(dst, "w", newline="\n") as f:
        f.write(header)

    print(f"written: {dst}")


if __name__ == "__main__":
    main()
